from . import product_compliant
from . import product_material
from . import product_material_class
from . import product_material_composition
from . import product_template
from . import res_config_settings
from . import sale_order
from . import stock_move_line
from . import product_material_waste_component
from . import product_material_waste_component_class
